import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link'; // Import Link component for navigation
import img from '../../public/assets/synapse.jpg';

export default function Home() {
  return (
    <div className="bg-gray-100 min-h-screen flex flex-col  items-center justify-center">
      <Head>
        <title>Real-Time Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-8 text-center">
        <h1 className="text-7xl font-bold mb-4 text-gray-800">Synapse Chat</h1>
        <p className="text-lg mb-8 text-gray-600">
          Our chat app lets you stay connected with the people who matter most.
        </p>

        <div className="w-full h-[600px] flex justify-center ">
          <img
            src={`/assets/synapse.jpg`}
            alt="Chat illustration"
            className="rounded-lg w-full mb-8 h-[550px] object-cover"
          />
        </div>

        <Link href="/login" className=''>
          <button className="bg-purple-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            Get Started
          </button>
        </Link>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-4 mt-8 w-full h-[200px] flex justify-center items-center">
        <p>&copy; 2024 SYNAPSE</p>
      </footer>
    </div>
  );
}