
// export default function Home() {
//   return (
//     <main className="">
//       <h1>Home</h1>
//     </main>
//   );
// }


// pages/index.js
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link'; // Import Link component for navigation
import img from '../../public/image img.png';

export default function Home() {

  return (
    <div className="bg-gray-100 min-h-screen flex flex-col items-center justify-center">
      <Head>
        <title>Real-Time Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-8 text-center">
        <h1 className="text-4xl font-bold mb-4 text-gray-800">
          Connect with friends and family in real-time
        </h1>
        <p className="text-lg mb-8 text-gray-600">
          Our chat app lets you stay connected with the people who matter most.
        </p>

        <Image
          src={img}          
          alt="Chat illustration"
          width={400}
          height={300}
          className="rounded-lg mb-8"
        />

        {/* Call to action button (redirects to login) */}
        <Link href="/login"> 
          <button
            className="bg-purple-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          >
            Get Started
          </button>
        </Link>

      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-4 mt-8">
        <div className="container mx-auto px-4 text-center">
          <p>&copy; 2023 SYNAPSE</p>
        </div>
      </footer>
    </div>
  );
}