export const loginUrl = "http://localhost:3000/auth/signin"
export const baseUrl = "http://localhost:3000"
export const baseUrlF = "http://localhost:3001"
export const signupUrl = "http://localhost:3000/auth/signup"
export const messagesUrl = "http://localhost:3000/messages"
export const usersUrl = "http://localhost:3000/auth/users"
export const conversationUrl = "http://localhost:3000/conversation"
export const currentUser = "http://localhost:3000/auth/currentuser"